import { spawnSync } from 'node:child_process';
import { existsSync, mkdirSync, writeFileSync } from 'node:fs';
import { join } from 'node:path';

import type { OnDoneOpts, TestProfile, ValidateFilesOpts } from '../types.js';

/**
 * Emits .config/nextest.toml in testsDir defining the [profile.ci] section
 * that `cargo nextest run --profile ci` requires.
 * --junit-path on the CLI overrides the output path at runtime.
 */
function writeNextestConfig(testsDir: string, force: boolean): void {
  const configDir = join(testsDir, '.config');
  const configPath = join(configDir, 'nextest.toml');
  if (existsSync(configPath) && !force) return;

  const content = `# Auto-generated by \`agents feat:design\`. Re-run to update.
[profile.ci]
test-output = "immediate-final"
`;
  mkdirSync(configDir, { recursive: true });
  writeFileSync(configPath, content, 'utf8');
  console.log(`[design-tests:rust-rusttest] Written ${configPath}`);
}

/**
 * Best-effort compile check for generated Rust test files using `cargo check --tests`.
 * Requires mod.rs files to already have been generated (onDone runs before validateFiles).
 * Skips silently if `cargo` is not on PATH.
 */
function rusttestValidateFiles(opts: ValidateFilesOpts): void {
  const { testsDir, generatedFiles } = opts;
  if (generatedFiles.length === 0) return;
  if (!generatedFiles.some((f) => f.endsWith('.rs'))) return;

  console.log(`\nValidating generated spec files (cargo check --tests)...`);
  try {
    const result = spawnSync('cargo', ['check', '--tests'], {
      cwd: testsDir,
      encoding: 'utf8',
      timeout: 60_000,
    });
    if (result.error) throw result.error; // binary not found → ENOENT
    if (result.status === 0) {
      console.log(`  Rust validation passed.`);
    } else {
      const output = (result.stdout ?? '') + (result.stderr ?? '');
      console.error(`  ${opts.errMessage}`);
      for (const line of output.split('\n').filter(Boolean).slice(0, 20)) {
        console.error(`    ${line}`);
      }
      process.exit(1);
    }
  } catch {
    console.warn(`  Rust validation skipped (cargo not available).`);
  }
}

/**
 * Writes Cargo.toml for the test crate if it doesn't exist yet.
 * The coder agent generates .rs files but cannot be expected to produce a
 * well-formed Cargo.toml, so the scaffold emits a minimal one here.
 */
function writeCargoToml(testsDir: string, force: boolean): void {
  const cargoTomlPath = join(testsDir, 'Cargo.toml');
  if (existsSync(cargoTomlPath) && !force) return;

  const content = `# Auto-generated by \`agents feat:design\`. Re-run to update.
[package]
name = "factory-tests"
version = "0.1.0"
edition = "2021"

[dev-dependencies]
reqwest = { version = "0.11", features = ["blocking", "json"] }
serde = { version = "1", features = ["derive"] }
serde_json = "1"
tokio = { version = "1", features = ["full"] }
`;
  writeFileSync(cargoTomlPath, content, 'utf8');
  console.log(`[design-tests:rust-rusttest] Written ${cargoTomlPath}`);
}

/**
 * Emits mod.rs in public/ and hidden/ listing every generated .rs module so
 * `cargo nextest run` can discover them, and writes .config/nextest.toml
 * defining the [profile.ci] section required by test.sh.
 */
function rusttestOnDone(opts: OnDoneOpts): void {
  const { testsDir, generatedFiles, force } = opts;

  writeNextestConfig(testsDir, force);
  writeCargoToml(testsDir, force);

  for (const subdir of ['public', 'hidden'] as const) {
    const subdirPath = join(testsDir, subdir);
    if (!existsSync(subdirPath)) continue;

    const modules = generatedFiles
      .filter((f) => f.startsWith(`${subdir}/`) && f.endsWith('.rs'))
      .map((f) => f.slice(`${subdir}/`.length).replace(/\.rs$/, ''));

    if (modules.length === 0) continue;

    const modRsPath = join(subdirPath, 'mod.rs');
    const modRsContent =
      `// Auto-generated by \`agents feat:design\`. Re-run to update.\n` +
      modules.map((m) => `pub mod ${m};`).join('\n') +
      '\n';

    if (!existsSync(modRsPath) || force) {
      writeFileSync(modRsPath, modRsContent, 'utf8');
      console.log(`[design-tests:rust-rusttest] Written ${modRsPath}`);
      generatedFiles.push(`${subdir}/mod.rs`);
    }
  }
}

export const rusttestProfile: TestProfile = {
  id: 'rust-rusttest',
  language: 'Rust',
  framework: 'cargo test',
  specExtension: '.rs',
  fileNamingRule:
    'Files use ".rs" suffix (e.g. "public/happy_path.rs"). Every spec file MUST be declared in the corresponding mod.rs (auto-generated). Test functions MUST be annotated with `#[test]` or `#[tokio::test]`.',
  helpersFilename: 'helpers.rs',
  infraFilename: 'infra_test.rs',
  importRules:
    'Include `use crate::helpers::{exec_sidecar, base_url, http_request};` at the top of each spec file. Use `#[cfg(test)]` + `mod tests { ... }` or top-level `#[test]` functions.',
  assertionRules:
    'Use `assert_eq!`, `assert!`, `assert!(result.contains(...))`. For async tests, annotate with `#[tokio::test]`. Return `Result<(), Box<dyn std::error::Error>>` for fallible tests.',
  onDone: rusttestOnDone,
  validateFiles: rusttestValidateFiles,
};
