#!/bin/sh
# Test Runner Container Entrypoint — Rust / cargo test runner
#
# CONTRACT — this script defines the interface between the Orchestrator and the Test Runner image.
# It is always bind-mounted into the container at /usr/local/bin/test.sh (read-only).
# Override by passing --test-script <path> to run / resume / run test / design-fail2pass.
#
# Environment variables provided by the Orchestrator (all required):
#
#   SAIFAC_TARGET_URL    URL of the application under test (web server or sidecar).
#   SAIFAC_SIDECAR_URL   URL of the HTTP sidecar that wraps CLI command execution.
#   SAIFAC_FEATURE_NAME  Name of the Saifac feature being tested.
#   SAIFAC_TESTS_DIR     Absolute path inside the container where test files are mounted.
#                         Default: /tests
#                         Subdirectories:
#                           /tests/public/        — public spec files (*.rs, visible to agent)
#                           /tests/hidden/        — hidden spec files (*.rs, not exposed)
#                           /tests/helpers.rs     — shared test helpers
#                           /tests/infra_test.rs  — infra health-check (always present)
#                           /tests/public/mod.rs  — auto-generated module index
#                           /tests/hidden/mod.rs  — auto-generated module index
#   SAIFAC_OUTPUT_FILE   Absolute path where this script must write the JUnit XML report.
#
# Exit code contract:
#   0  — all tests passed
#   non-zero — one or more tests failed (or runner error)
#
# Requires: cargo-nextest (pre-installed in the Docker image)

set -e

echo "[test-runner] SAIFAC_TARGET_URL:   ${SAIFAC_TARGET_URL}"
echo "[test-runner] SAIFAC_SIDECAR_URL:  ${SAIFAC_SIDECAR_URL}"
echo "[test-runner] SAIFAC_FEATURE_NAME: ${SAIFAC_FEATURE_NAME}"
echo "[test-runner] SAIFAC_TESTS_DIR:    ${SAIFAC_TESTS_DIR}"
echo "[test-runner] SAIFAC_OUTPUT_FILE:  ${SAIFAC_OUTPUT_FILE}"

echo "[test-runner] public spec count:  $(find "${SAIFAC_TESTS_DIR}/public" -name '*.rs' ! -name 'mod.rs' 2>/dev/null | wc -l | tr -d ' ')"
echo "[test-runner] hidden spec count:  $(find "${SAIFAC_TESTS_DIR}/hidden" -name '*.rs' ! -name 'mod.rs' 2>/dev/null | wc -l | tr -d ' ')"

cd "${SAIFAC_TESTS_DIR}"

# cargo-nextest produces JUnit XML natively.
# --profile ci must be defined in .cargo/nextest.toml (or nextest.toml) in the test crate.
# .config/nextest.toml (with [profile.ci]) is auto-generated by the onDone hook.
exec cargo nextest run \
  --profile ci \
  --test-output immediate-final \
  --junit-path "${SAIFAC_OUTPUT_FILE}"
