#!/bin/sh
# Test Runner Container Entrypoint — TypeScript / Playwright runner
#
# CONTRACT — this script defines the interface between the Orchestrator and the Test Runner image.
# It is always bind-mounted into the container at /usr/local/bin/test.sh (read-only).
# Override by passing --test-script <path> to run / resume / run test / design-fail2pass.
#
# Environment variables provided by the Orchestrator (all required):
#
#   SAIFAC_TARGET_URL    URL of the application under test (web server or sidecar).
#   SAIFAC_SIDECAR_URL   URL of the HTTP sidecar that wraps CLI command execution.
#   SAIFAC_FEATURE_NAME  Name of the Saifac feature being tested.
#   SAIFAC_TESTS_DIR     Absolute path inside the container where test files are mounted.
#                         Default: /tests
#                         Subdirectories:
#                           /tests/public/          — public spec files (visible to agent)
#                           /tests/hidden/          — hidden spec files (not exposed to agent)
#                           /tests/helpers.ts       — shared test helpers imported by specs
#                           /tests/infra.spec.ts    — infra health-check (always present)
#                           /tests/playwright.config.ts — Playwright config (auto-generated)
#   SAIFAC_OUTPUT_FILE   Absolute path where this script must write the JUnit XML report.
#
# Exit code contract:
#   0  — all tests passed
#   non-zero — one or more tests failed (or runner error)

set -e

echo "[test-runner] SAIFAC_TARGET_URL:   ${SAIFAC_TARGET_URL}"
echo "[test-runner] SAIFAC_SIDECAR_URL:  ${SAIFAC_SIDECAR_URL}"
echo "[test-runner] SAIFAC_FEATURE_NAME: ${SAIFAC_FEATURE_NAME}"
echo "[test-runner] SAIFAC_TESTS_DIR:    ${SAIFAC_TESTS_DIR}"
echo "[test-runner] SAIFAC_OUTPUT_FILE:  ${SAIFAC_OUTPUT_FILE}"

echo "[test-runner] public spec count:  $(find "${SAIFAC_TESTS_DIR}/public" -name '*.spec.ts' 2>/dev/null | wc -l | tr -d ' ')"
echo "[test-runner] hidden spec count:  $(find "${SAIFAC_TESTS_DIR}/hidden" -name '*.spec.ts' 2>/dev/null | wc -l | tr -d ' ')"

cd "${SAIFAC_TESTS_DIR}"

# Run Playwright tests. playwright.config.ts (generated by onDone hook) sets:
#   reporter: [['junit', { outputFile: process.env.SAIFAC_OUTPUT_FILE }]]
#   use.baseURL: process.env.SAIFAC_TARGET_URL
exec npx playwright test \
  --config="${SAIFAC_TESTS_DIR}/playwright.config.ts"
