#!/bin/sh
# Test Runner Container Entrypoint — TypeScript / Playwright runner
#
# CONTRACT — this script defines the interface between the Orchestrator and the Test Runner image.
# It is always bind-mounted into the container at /usr/local/bin/test.sh (read-only).
# Override by passing --test-script <path> to run / resume / run test / design-fail2pass.
#
# Environment variables provided by the Orchestrator (all required):
#
#   SAIFCTL_TARGET_URL    URL of the application under test (web server or sidecar).
#   SAIFCTL_SIDECAR_URL   URL of the HTTP sidecar that wraps CLI command execution.
#   SAIFCTL_FEATURE_NAME  Name of the Saifctl feature being tested.
#   SAIFCTL_TESTS_DIR     Absolute path inside the container where test files are mounted.
#                         Default: /tests
#                         Layout depends on whether the orchestrator merged multiple
#                         test-scope sources (e.g. feature/tests + saifctl/tests):
#                           Single-source (the common case) — flat layout:
#                             /tests/public/        — public spec files (visible to agent)
#                             /tests/hidden/        — hidden spec files (not exposed to agent)
#                             /tests/helpers.ts     — shared test helpers imported by specs
#                             /tests/infra.spec.ts  — infra health-check (always present)
#                             /tests/playwright.config.ts — Playwright config (auto-generated)
#                           Multi-source — per-label subtrees:
#                             /tests/<label>/public/        — same content, namespaced
#                             /tests/<label>/hidden/
#                             /tests/<label>/helpers.ts     — per-source, no shared singleton
#                             /tests/<label>/infra.spec.ts
#                         Either way, Playwright's recursive **/*.spec.ts discovery finds them.
#   SAIFCTL_OUTPUT_FILE   Absolute path where this script must write the JUnit XML report.
#
# Exit code contract:
#   0  — all tests passed
#   non-zero — one or more tests failed (or runner error)

set -e

echo "[test-runner] SAIFCTL_TARGET_URL:   ${SAIFCTL_TARGET_URL}"
echo "[test-runner] SAIFCTL_SIDECAR_URL:  ${SAIFCTL_SIDECAR_URL}"
echo "[test-runner] SAIFCTL_FEATURE_NAME: ${SAIFCTL_FEATURE_NAME}"
echo "[test-runner] SAIFCTL_TESTS_DIR:    ${SAIFCTL_TESTS_DIR}"
echo "[test-runner] SAIFCTL_OUTPUT_FILE:  ${SAIFCTL_OUTPUT_FILE}"

echo "[test-runner] public spec count:  $(find "${SAIFCTL_TESTS_DIR}" -path '*/public/*' -name '*.spec.ts' 2>/dev/null | wc -l | tr -d ' ')"
echo "[test-runner] hidden spec count:  $(find "${SAIFCTL_TESTS_DIR}" -path '*/hidden/*' -name '*.spec.ts' 2>/dev/null | wc -l | tr -d ' ')"

cd "${SAIFCTL_TESTS_DIR}"

# Run Playwright tests. playwright.config.ts (generated by onDone hook) sets:
#   reporter: [['junit', { outputFile: process.env.SAIFCTL_OUTPUT_FILE }]]
#   use.baseURL: process.env.SAIFCTL_TARGET_URL
exec npx playwright test \
  --config="${SAIFCTL_TESTS_DIR}/playwright.config.ts"
