#!/bin/sh
# Test Runner Container Entrypoint — TypeScript / Playwright runner
#
# CONTRACT — this script defines the interface between the Orchestrator and the Test Runner image.
# It is always bind-mounted into the container at /usr/local/bin/test.sh (read-only).
# Override by passing --test-script <path> to feat:run / feat:continue / feat:assess / feat:fail2pass.
#
# Environment variables provided by the Orchestrator (all required):
#
#   FACTORY_TARGET_URL    URL of the application under test (web server or sidecar).
#   FACTORY_SIDECAR_URL   URL of the HTTP sidecar that wraps CLI command execution.
#   FACTORY_CHANGE_NAME   Name of the OpenSpec change being assessed.
#   FACTORY_TESTS_DIR     Absolute path inside the container where test files are mounted.
#                         Default: /tests
#                         Subdirectories:
#                           /tests/public/          — public spec files (visible to agent)
#                           /tests/hidden/          — hidden spec files (not exposed to agent)
#                           /tests/helpers.ts       — shared test helpers imported by specs
#                           /tests/infra.spec.ts    — infra health-check (always present)
#                           /tests/playwright.config.ts — Playwright config (auto-generated)
#   FACTORY_OUTPUT_FILE   Absolute path where this script must write the JUnit XML report.
#
# Exit code contract:
#   0  — all tests passed
#   non-zero — one or more tests failed (or runner error)

set -e

echo "[test-runner] FACTORY_TARGET_URL:   ${FACTORY_TARGET_URL}"
echo "[test-runner] FACTORY_SIDECAR_URL:  ${FACTORY_SIDECAR_URL}"
echo "[test-runner] FACTORY_CHANGE_NAME:  ${FACTORY_CHANGE_NAME}"
echo "[test-runner] FACTORY_TESTS_DIR:    ${FACTORY_TESTS_DIR}"
echo "[test-runner] FACTORY_OUTPUT_FILE:  ${FACTORY_OUTPUT_FILE}"

echo "[test-runner] public spec count:  $(find "${FACTORY_TESTS_DIR}/public" -name '*.spec.ts' 2>/dev/null | wc -l | tr -d ' ')"
echo "[test-runner] hidden spec count:  $(find "${FACTORY_TESTS_DIR}/hidden" -name '*.spec.ts' 2>/dev/null | wc -l | tr -d ' ')"

cd "${FACTORY_TESTS_DIR}"

# Run Playwright tests. playwright.config.ts (generated by onDone hook) sets:
#   reporter: [['junit', { outputFile: process.env.FACTORY_OUTPUT_FILE }]]
#   use.baseURL: process.env.FACTORY_TARGET_URL
exec npx playwright test \
  --config="${FACTORY_TESTS_DIR}/playwright.config.ts"
