/* eslint-disable */
// @ts-nocheck
/**
 * Test helpers for the Software Factory test runner.
 * Auto-generated by `agents feat:design`.
 * Do not edit; regenerate with `agents feat:design <changeName>`.
 */

export interface SidecarResponse {
  stdout: string;
  stderr: string;
  exitCode: number;
}

/**
 * Execute a command in the staging container via the HTTP sidecar.
 *
 * FACTORY_SIDECAR_URL is injected by the Orchestrator (e.g. http://staging:8080/exec).
 * Falls back to localhost for local development without the Orchestrator.
 */
export async function execSidecar(
  cmd: string,
  args: string[] = [],
  env: Record<string, string> = {},
): Promise<SidecarResponse> {
  const url = process.env.FACTORY_SIDECAR_URL ?? 'http://localhost:8080/exec';
  const res = await fetch(url, {
    method: 'POST',
    headers: { 'Content-Type': 'application/json' },
    body: JSON.stringify({ cmd, args, env }),
  });
  if (!res.ok) throw new Error(`Sidecar request failed: ${res.status}`);
  return res.json() as Promise<SidecarResponse>;
}

/**
 * Returns the base URL for the web application in the staging container.
 *
 * FACTORY_TARGET_URL is injected by the Orchestrator. Falls back to staging:3000
 * for local development without the Orchestrator.
 */
export function baseUrl(): string {
  return process.env.FACTORY_TARGET_URL ?? 'http://staging:3000';
}

/**
 * Make an HTTP request to the staging container web application.
 */
export async function httpRequest(opts: {
  method: string;
  path: string;
  headers?: Record<string, string>;
  body?: unknown;
}): Promise<Response> {
  const { method, path, headers = {}, body } = opts;
  const url = baseUrl().replace(/\/$/, '') + path;
  return fetch(url, {
    method,
    headers: { 'Content-Type': 'application/json', ...headers },
    ...(body != null ? { body: JSON.stringify(body) } : {}),
  });
}
