/* eslint-disable */
// @ts-nocheck
/**
 * Infrastructure health checks — auto-generated by `agents feat:design`.
 * Validates the sidecar HTTP→exec path before feature tests run.
 * These tests are NOT in the change spec and cannot be tampered with by the coder.
 *
 * Uses FACTORY_SIDECAR_URL (injected by the Orchestrator). The sidecar runs in every
 * staging container regardless of project type.
 */
import { test, expect } from '@playwright/test';
import { execSidecar } from './helpers.js';

test.describe('sidecar:health', () => {
  test('[infra-001] sidecar responds to a known-good command (echo)', async () => {
    const { stdout, stderr, exitCode } = await execSidecar('echo', ['sidecar-ok']);
    expect(exitCode).toBe(0);
    expect(stdout.trim()).toBe('sidecar-ok');
    expect(stderr).toBe('');
  });

  test('[infra-002] sidecar returns exit code 1 for a failing command', async () => {
    const { exitCode, stderr } = await execSidecar('sh', [
      '-c',
      'echo "expected-failure-output" >&2 && exit 1',
    ]);
    expect(exitCode).toBe(1);
    expect(stderr).toContain('expected-failure-output');
  });
});
