#!/bin/sh
# Test Runner Container Entrypoint — Rust / cargo test with Playwright stub
#
# CONTRACT — this script defines the interface between the Orchestrator and the Test Runner image.
# It is always bind-mounted into the container at /usr/local/bin/test.sh (read-only).
# Override by passing --test-script <path> to feat:run / feat:continue / feat:assess / feat:fail2pass.
#
# Environment variables provided by the Orchestrator (all required):
#
#   FACTORY_TARGET_URL    URL of the application under test.
#   FACTORY_SIDECAR_URL   URL of the HTTP sidecar.
#   FACTORY_CHANGE_NAME   Name of the OpenSpec change being assessed.
#   FACTORY_TESTS_DIR     Absolute path inside the container where test files are mounted.
#   FACTORY_OUTPUT_FILE   Absolute path where this script must write the JUnit XML report.

set -e

echo "[test-runner] FACTORY_TARGET_URL:   ${FACTORY_TARGET_URL}"
echo "[test-runner] FACTORY_SIDECAR_URL:  ${FACTORY_SIDECAR_URL}"
echo "[test-runner] FACTORY_CHANGE_NAME:  ${FACTORY_CHANGE_NAME}"
echo "[test-runner] FACTORY_TESTS_DIR:    ${FACTORY_TESTS_DIR}"
echo "[test-runner] FACTORY_OUTPUT_FILE:  ${FACTORY_OUTPUT_FILE}"

cd "${FACTORY_TESTS_DIR}"

# cargo-nextest produces JUnit XML natively.
# --profile ci must be defined in .cargo/nextest.toml (or nextest.toml) in the test crate.
# .config/nextest.toml (with [profile.ci]) is auto-generated by the onDone hook.
exec cargo nextest run \
  --profile ci \
  --test-output immediate-final \
  --junit-path "${FACTORY_OUTPUT_FILE}"
