#!/bin/sh
# Test Runner Container Entrypoint — Rust / cargo test with Playwright stub
#
# CONTRACT — this script defines the interface between the Orchestrator and the Test Runner image.
# It is always bind-mounted into the container at /usr/local/bin/test.sh (read-only).
# Override by passing --test-script <path> to run / resume / run test / design-fail2pass.
#
# Environment variables provided by the Orchestrator (all required):
#
#   SAIFCTL_TARGET_URL    URL of the application under test.
#   SAIFCTL_SIDECAR_URL   URL of the HTTP sidecar.
#   SAIFCTL_FEATURE_NAME  Name of the Saifctl feature being tested.
#   SAIFCTL_TESTS_DIR     Absolute path inside the container where test files are mounted.
#   SAIFCTL_OUTPUT_FILE   Absolute path where this script must write the JUnit XML report.

set -e

echo "[test-runner] SAIFCTL_TARGET_URL:   ${SAIFCTL_TARGET_URL}"
echo "[test-runner] SAIFCTL_SIDECAR_URL:  ${SAIFCTL_SIDECAR_URL}"
echo "[test-runner] SAIFCTL_FEATURE_NAME: ${SAIFCTL_FEATURE_NAME}"
echo "[test-runner] SAIFCTL_TESTS_DIR:    ${SAIFCTL_TESTS_DIR}"
echo "[test-runner] SAIFCTL_OUTPUT_FILE:  ${SAIFCTL_OUTPUT_FILE}"

cd "${SAIFCTL_TESTS_DIR}"

# cargo-nextest produces JUnit XML natively.
# --profile ci must be defined in .cargo/nextest.toml (or nextest.toml) in the test crate.
# .config/nextest.toml (with [profile.ci]) is auto-generated by the onDone hook.
exec cargo nextest run \
  --profile ci \
  --test-output immediate-final \
  --junit-path "${SAIFCTL_OUTPUT_FILE}"
