"""
Test helpers for the Software Factory test runner.
Auto-generated by `agents feat:design`.
Do not edit; regenerate with `agents feat:design <changeName>`.
"""
from __future__ import annotations

import json
import os
from dataclasses import dataclass
from typing import Any

import requests


@dataclass
class SidecarResponse:
    stdout: str
    stderr: str
    exit_code: int


def exec_sidecar(
    cmd: str,
    args: list[str] | None = None,
    env: dict[str, str] | None = None,
) -> SidecarResponse:
    """Execute a command in the staging container via the HTTP sidecar.

    FACTORY_SIDECAR_URL is injected by the Orchestrator (e.g. http://staging:8080/exec).
    Falls back to localhost for local development without the Orchestrator.
    """
    url = os.environ.get("FACTORY_SIDECAR_URL", "http://localhost:8080/exec")
    payload: dict[str, Any] = {"cmd": cmd, "args": args or [], "env": env or {}}
    resp = requests.post(url, json=payload, timeout=30)
    resp.raise_for_status()
    data = resp.json()
    return SidecarResponse(
        stdout=data.get("stdout", ""),
        stderr=data.get("stderr", ""),
        exit_code=data.get("exitCode", -1),
    )


def base_url() -> str:
    """Returns the base URL for the web application in the staging container.

    FACTORY_TARGET_URL is injected by the Orchestrator. Falls back to staging:3000
    for local development without the Orchestrator.
    """
    return os.environ.get("FACTORY_TARGET_URL", "http://staging:3000")


def http_request(
    method: str,
    path: str,
    headers: dict[str, str] | None = None,
    body: Any = None,
) -> requests.Response:
    """Make an HTTP request to the staging container web application."""
    url = base_url().rstrip("/") + path
    default_headers = {"Content-Type": "application/json"}
    if headers:
        default_headers.update(headers)
    kwargs: dict[str, Any] = {"headers": default_headers, "timeout": 30}
    if body is not None:
        kwargs["data"] = json.dumps(body)
    return requests.request(method, url, **kwargs)
