"""
Infrastructure health checks — auto-generated by `agents feat:design`.
Validates the sidecar HTTP->exec path before feature tests run.
These tests are NOT in the change spec and cannot be tampered with by the coder.

Uses FACTORY_SIDECAR_URL (injected by the Orchestrator). The sidecar runs in every
staging container regardless of project type.
"""

import pytest

from .helpers import exec_sidecar


class TestSidecarHealth:
    def test_infra_001_sidecar_responds_to_known_good_command(self) -> None:
        """[infra-001] sidecar responds to a known-good command (echo)"""
        result = exec_sidecar("echo", ["sidecar-ok"])
        assert result.exit_code == 0
        assert result.stdout.strip() == "sidecar-ok"
        assert result.stderr == ""

    def test_infra_002_sidecar_returns_exit_code_1_for_failing_command(self) -> None:
        """[infra-002] sidecar returns exit code 1 for a failing command"""
        result = exec_sidecar(
            "sh", ["-c", 'echo "expected-failure-output" >&2 && exit 1']
        )
        assert result.exit_code == 1
        assert "expected-failure-output" in result.stderr
