//! Test helpers for the Software Factory test runner.
//! Auto-generated by `agents feat:design`.
//! Do not edit; regenerate with `agents feat:design <changeName>`.

use std::collections::HashMap;
use std::env;

use playwright::Playwright;
use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize)]
pub struct SidecarResponse {
    pub stdout: String,
    pub stderr: String,
    #[serde(rename = "exitCode")]
    pub exit_code: i32,
}

#[derive(Serialize)]
struct SidecarRequest<'a> {
    cmd: &'a str,
    args: &'a [&'a str],
    env: HashMap<&'a str, &'a str>,
}

/// Execute a command in the staging container via the HTTP sidecar.
///
/// `FACTORY_SIDECAR_URL` is injected by the Orchestrator (e.g. `http://staging:8080/exec`).
/// Falls back to `http://localhost:8080/exec` for local development.
pub fn exec_sidecar(
    cmd: &str,
    args: &[&str],
    env: HashMap<&str, &str>,
) -> Result<SidecarResponse, Box<dyn std::error::Error>> {
    let url = env::var("FACTORY_SIDECAR_URL")
        .unwrap_or_else(|_| "http://localhost:8080/exec".to_string());

    let payload = SidecarRequest { cmd, args, env };
    let client = reqwest::blocking::Client::new();
    let resp = client
        .post(&url)
        .json(&payload)
        .send()?
        .json::<SidecarResponse>()?;

    Ok(resp)
}

/// Returns the base URL for the web application in the staging container.
///
/// `FACTORY_TARGET_URL` is injected by the Orchestrator. Falls back to `http://staging:3000`.
pub fn base_url() -> String {
    env::var("FACTORY_TARGET_URL").unwrap_or_else(|_| "http://staging:3000".to_string())
}

/// Make an HTTP request to the staging container web application.
pub fn http_request(
    method: &str,
    path: &str,
    headers: HashMap<&str, &str>,
    body: Option<serde_json::Value>,
) -> Result<reqwest::blocking::Response, Box<dyn std::error::Error>> {
    let url = format!("{}{}", base_url().trim_end_matches('/'), path);
    let client = reqwest::blocking::Client::new();

    let mut req = client.request(method.parse()?, &url);
    req = req.header("Content-Type", "application/json");
    for (k, v) in headers {
        req = req.header(k, v);
    }
    if let Some(b) = body {
        req = req.json(&b);
    }

    Ok(req.send()?)
}

/// Launch a Playwright browser and return a Page pointed at `base_url()`.
///
/// # Example
/// ```rust
/// let (pw, browser, page) = new_page().await?;
/// page.goto_builder(&base_url()).goto().await?;
/// browser.close().await?;
/// drop(pw);
/// ```
pub async fn new_page() -> Result<
    (Playwright, playwright::api::Browser, playwright::api::Page),
    Box<dyn std::error::Error>,
> {
    let pw = Playwright::initialize().await?;
    let chromium = pw.chromium();
    let browser = chromium.launcher().launch().await?;
    let context = browser
        .context_builder()
        .base_url(&base_url())
        .build()
        .await?;
    let page = context.new_page().await?;
    Ok((pw, browser, page))
}
