//! Infrastructure health checks — auto-generated by `agents feat:design`.
//! Validates both the sidecar HTTP->exec path and browser connectivity before feature tests run.
//! These tests are NOT in the change spec and cannot be tampered with by the coder.

use std::collections::HashMap;

use crate::helpers::{base_url, exec_sidecar, new_page};

/// [infra-001] sidecar responds to a known-good command (echo)
#[test]
fn infra_001_sidecar_responds_to_known_good_command() {
    let result = exec_sidecar("echo", &["sidecar-ok"], HashMap::new())
        .expect("[infra-001] sidecar request failed");
    assert_eq!(result.exit_code, 0, "[infra-001] expected exit code 0");
    assert_eq!(
        result.stdout.trim(),
        "sidecar-ok",
        "[infra-001] expected stdout 'sidecar-ok'"
    );
    assert_eq!(result.stderr, "", "[infra-001] expected empty stderr");
}

/// [infra-002] sidecar returns exit code 1 for a failing command
#[test]
fn infra_002_sidecar_returns_exit_code_1_for_failing_command() {
    let result = exec_sidecar(
        "sh",
        &["-c", r#"echo "expected-failure-output" >&2 && exit 1"#],
        HashMap::new(),
    )
    .expect("[infra-002] sidecar request failed");
    assert_eq!(result.exit_code, 1, "[infra-002] expected exit code 1");
    assert!(
        result.stderr.contains("expected-failure-output"),
        "[infra-002] expected stderr to contain 'expected-failure-output', got {:?}",
        result.stderr
    );
}

/// [infra-003] Playwright browser can reach the staging container
#[tokio::test]
async fn infra_003_browser_can_reach_staging() {
    let (_pw, browser, page) = new_page().await.expect("[infra-003] failed to open browser page");
    let response = page
        .goto_builder(&base_url())
        .goto()
        .await
        .expect("[infra-003] page.goto failed");
    let status = response.status().expect("[infra-003] could not read response status");
    assert!(status < 500, "[infra-003] staging returned server error {}", status);
    browser.close().await.ok();
}
