/**
 * Write tests — Phase 2 of the tests design workflow.
 *
 * Reads tests.json, then writes the tests files into the
 * feature's tests/ directory:
 *   - helpers.<ext>    — shared transport helpers (execSidecar, httpRequest, baseUrl)
 *   - infra.<ext>      — sidecar health checks (always present for CLI projects)
 *   - public/<test_name>.<ext>, hidden/<test_name>.<ext> — AI-generated spec files for each entrypoint
 *
 * The file extension and naming convention is determined by the TestProfile.
 * By default existing files are never overwritten. Pass force: true to overwrite.
 */

import { mkdir } from 'node:fs/promises';
import { dirname, join } from 'node:path';

import { getSaifctlRoot } from '../constants.js';
import { type LlmOverrides } from '../llm-config.js';
import { consola } from '../logger.js';
import type { Feature } from '../specs/discover.js';
import { type TestProfile } from '../test-profiles/index.js';
import type { DrainableChunk } from '../utils/drain-stream.js';
import { pathExists, readUtf8, writeUtf8 } from '../utils/io.js';
import { runTestsWriterAgent } from './agents/tests-writer.js';
import { TestCatalogSchema } from './schema.js';

const _srcDir = join(getSaifctlRoot(), 'src');

/** Reads a template file from src/test-profiles/<profileId>/templates/<filename>. */
async function readTemplate(profileId: string, filename: string): Promise<string> {
  return readUtf8(join(_srcDir, 'test-profiles', profileId, 'templates', filename));
}

export interface GenerateTestsOpts {
  /** Resolved feature (name, absolutePath, relativePath). */
  feature: Feature;
  /**
   * When true, overwrite existing spec files (helpers, infra, and all entrypoint
   * files). Existing files are preserved by default so human edits are not lost.
   */
  force?: boolean;
  /** Test profile determines language, templates, and coder agent instructions. Defaults to vitest. */
  testProfile: TestProfile;
  /** Effective LLM config (--model / --base-url). */
  llm?: LlmOverrides;
  /** Called with text deltas from LLM generation (for live display) */
  onThought?: (delta: string) => void;
  /** Called with each fullStream chunk */
  onEvent?: (chunk: DrainableChunk) => void;
  abortSignal?: AbortSignal;
}

export interface GenerateTestsResult {
  catalogPath: string;
  testCaseCount: number;
  /** Absolute path to tests/ directory. */
  testsDir: string;
  /** Entrypoints that were newly generated (skipped = already existed). */
  generatedFiles: string[];
  /** Entrypoints that were skipped because they already existed. */
  skippedFiles: string[];
}

/**
 * Reads tests.json and generates test scaffolding.
 *
 * Static files (helpers, infra) are written from profile-specific templates.
 * Feature spec files (public/*, hidden/*) are generated by the tests-writer LLM agent.
 * Each unique entrypoint in tests.json gets one agent call, with all test cases for that
 * file passed together so the agent can write a cohesive suite.
 *
 * For Rust, also emits public/mod.rs and hidden/mod.rs declaring all generated modules
 * so `cargo test` can discover them.
 *
 * Expects tests.json to already exist (produced by `saifctl feat design`).
 */
export async function generateTests(opts: GenerateTestsOpts): Promise<GenerateTestsResult> {
  const { feature, force = false, testProfile, llm = {}, onThought, onEvent, abortSignal } = opts;

  const testsDir = join(feature.absolutePath, 'tests');
  const catalogPath = join(testsDir, 'tests.json');

  if (!(await pathExists(catalogPath))) {
    throw new Error(
      `tests.json not found at ${catalogPath}. Run 'saifctl feat design -n ${feature.name}' first.`,
    );
  }

  consola.log(`[design-tests:write] Reading ${catalogPath}`);
  consola.log(
    `[design-tests:write] Test profile: ${testProfile.id} (${testProfile.language} / ${testProfile.framework})`,
  );
  const rawJson = JSON.parse(await readUtf8(catalogPath)) as unknown;

  const parseResult = TestCatalogSchema.safeParse(rawJson);
  if (!parseResult.success) {
    throw new Error(
      `tests.json failed schema validation:\n${JSON.stringify(parseResult.error.issues, null, 2)}`,
    );
  }

  const catalog = parseResult.data;
  consola.log(`[design-tests:write] Loaded ${catalog.testCases.length} test cases`);

  // Write shared helpers from the profile's template — skip if already exists (unless force).
  const helpersPath = join(testsDir, testProfile.helpersFilename);
  if (!(await pathExists(helpersPath)) || force) {
    const helpersTemplate = await readTemplate(testProfile.id, testProfile.helpersFilename);
    await writeUtf8(helpersPath, helpersTemplate);
    consola.log(`[design-tests:write] Written ${helpersPath}`);
  } else {
    consola.log(`[design-tests:write] Skipped ${helpersPath} (already exists)`);
  }

  // Write sidecar health checks from the profile's template, if the profile has one.
  if (testProfile.infraFilename) {
    const infraPath = join(testsDir, testProfile.infraFilename);
    if (!(await pathExists(infraPath)) || force) {
      const infraTemplate = await readTemplate(testProfile.id, testProfile.infraFilename);
      await writeUtf8(infraPath, infraTemplate);
      consola.log(`[design-tests:write] Written ${infraPath}`);
    } else {
      consola.log(`[design-tests:write] Skipped ${infraPath} (already exists)`);
    }
  }

  // Group test cases by entrypoint. Test cases without an entrypoint are skipped
  // (they may exist for documentation purposes only).
  const entrypointMap = new Map<string, (typeof catalog.testCases)[number][]>();
  for (const tc of catalog.testCases) {
    if (!tc.entrypoint) {
      consola.warn(`[design-tests:write] Test case ${tc.id} has no entrypoint — skipping`);
      continue;
    }
    const existing = entrypointMap.get(tc.entrypoint) ?? [];
    existing.push(tc);
    entrypointMap.set(tc.entrypoint, existing);
  }

  const generatedFiles: string[] = [];
  const skippedFiles: string[] = [];

  // Read helpers content to pass to the coder agent as context.
  const helpersContent = await readUtf8(helpersPath);

  // Generate spec files concurrently (bounded to avoid rate limits).
  const CONCURRENCY = 3;
  const entries = [...entrypointMap.entries()];

  for (let i = 0; i < entries.length; i += CONCURRENCY) {
    const batch = entries.slice(i, i + CONCURRENCY);

    await Promise.all(
      batch.map(async ([entrypoint, testCases]) => {
        const specPath = join(testsDir, entrypoint);

        if ((await pathExists(specPath)) && !force) {
          consola.log(`[design-tests:write] Skipped ${entrypoint} (already exists)`);
          skippedFiles.push(entrypoint);
          return;
        }

        consola.log(
          `[design-tests:write] Generating ${entrypoint} (${testCases.length} test cases)...`,
        );

        const source = await runTestsWriterAgent({
          entrypoint,
          testCases,
          helpersContent,
          testProfile,
          llm,
          onThought,
          onEvent,
          abortSignal,
        });

        await mkdir(dirname(specPath), { recursive: true });
        await writeUtf8(specPath, source);
        consola.log(`[design-tests:write] Generated ${specPath}`);
        generatedFiles.push(entrypoint);
      }),
    );
  }

  await testProfile.onDone?.({ testsDir, generatedFiles, force });

  return {
    catalogPath,
    testCaseCount: catalog.testCases.length,
    testsDir,
    generatedFiles,
    skippedFiles,
  };
}
