"""
Infrastructure health checks — auto-generated by `agents feat:design`.
Validates both the sidecar HTTP->exec path and browser connectivity before feature tests run.
These tests are NOT in the change spec and cannot be tampered with by the coder.

Uses FACTORY_SIDECAR_URL and FACTORY_TARGET_URL (injected by the Orchestrator).
"""

from playwright.sync_api import Page

from .helpers import base_url, exec_sidecar


class TestSidecarHealth:
    def test_infra_001_sidecar_responds_to_known_good_command(self) -> None:
        """[infra-001] sidecar responds to a known-good command (echo)"""
        result = exec_sidecar("echo", ["sidecar-ok"])
        assert result.exit_code == 0
        assert result.stdout.strip() == "sidecar-ok"
        assert result.stderr == ""

    def test_infra_002_sidecar_returns_exit_code_1_for_failing_command(self) -> None:
        """[infra-002] sidecar returns exit code 1 for a failing command"""
        result = exec_sidecar(
            "sh", ["-c", 'echo "expected-failure-output" >&2 && exit 1']
        )
        assert result.exit_code == 1
        assert "expected-failure-output" in result.stderr


class TestBrowserConnectivity:
    def test_infra_003_browser_can_reach_staging(self, page: Page) -> None:
        """[infra-003] Playwright browser can reach the staging container"""
        response = page.goto(base_url())
        # Any HTTP response (including 404) means the server is reachable.
        # A None response would mean a network-level failure.
        assert response is not None, (
            "[infra-003] page.goto returned None — staging unreachable"
        )
        assert response.status < 500, (
            f"[infra-003] staging returned server error {response.status}"
        )
