// Infrastructure health checks — auto-generated by `saifctl feat design`.
// Validates both the sidecar HTTP->exec path and browser connectivity before feature tests run.
// These tests are NOT in the feature spec and cannot be tampered with by the coder.
package infra_test

import (
	"strings"
	"testing"

	helpers "github.com/placeholder/factory-tests/helpers"
)

// TestInfra001SidecarRespondsToKnownGoodCommand verifies the sidecar responds
// to a known-good command (echo) with exit code 0 and correct stdout.
func TestInfra001SidecarRespondsToKnownGoodCommand(t *testing.T) {
	result, err := helpers.ExecSidecar("echo", []string{"sidecar-ok"}, nil)
	if err != nil {
		t.Fatalf("[infra-001] sidecar request failed: %v", err)
	}
	if result.ExitCode != 0 {
		t.Errorf("[infra-001] expected exit code 0, got %d", result.ExitCode)
	}
	if strings.TrimSpace(result.Stdout) != "sidecar-ok" {
		t.Errorf("[infra-001] expected stdout 'sidecar-ok', got %q", result.Stdout)
	}
	if result.Stderr != "" {
		t.Errorf("[infra-001] expected empty stderr, got %q", result.Stderr)
	}
}

// TestInfra002SidecarReturnsExitCode1ForFailingCommand verifies that a failing
// command causes the sidecar to return exit code 1 and stderr output.
func TestInfra002SidecarReturnsExitCode1ForFailingCommand(t *testing.T) {
	result, err := helpers.ExecSidecar(
		"sh",
		[]string{"-c", `echo "expected-failure-output" >&2 && exit 1`},
		nil,
	)
	if err != nil {
		t.Fatalf("[infra-002] sidecar request failed: %v", err)
	}
	if result.ExitCode != 1 {
		t.Errorf("[infra-002] expected exit code 1, got %d", result.ExitCode)
	}
	if !strings.Contains(result.Stderr, "expected-failure-output") {
		t.Errorf("[infra-002] expected stderr to contain 'expected-failure-output', got %q", result.Stderr)
	}
}

// TestInfra003BrowserCanReachStaging verifies Playwright can open the staging app.
func TestInfra003BrowserCanReachStaging(t *testing.T) {
	page, browser, pw, err := helpers.NewPage()
	if err != nil {
		t.Fatalf("[infra-003] failed to open browser page: %v", err)
	}
	defer pw.Stop()
	defer browser.Close()

	resp, err := page.Goto(helpers.BaseURL())
	if err != nil {
		t.Fatalf("[infra-003] page.Goto failed: %v", err)
	}
	if resp == nil {
		t.Fatal("[infra-003] page.Goto returned nil response — staging unreachable")
	}
	if resp.Status() >= 500 {
		t.Errorf("[infra-003] staging returned server error %d", resp.Status())
	}
}
