//! Infrastructure health checks — auto-generated by `agents feat:design`.
//! Validates the sidecar HTTP->exec path before feature tests run.
//! These tests are NOT in the change spec and cannot be tampered with by the coder.

use std::collections::HashMap;

use crate::helpers::exec_sidecar;

/// [infra-001] sidecar responds to a known-good command (echo)
#[test]
fn infra_001_sidecar_responds_to_known_good_command() {
    let result = exec_sidecar("echo", &["sidecar-ok"], HashMap::new())
        .expect("[infra-001] sidecar request failed");
    assert_eq!(result.exit_code, 0, "[infra-001] expected exit code 0");
    assert_eq!(
        result.stdout.trim(),
        "sidecar-ok",
        "[infra-001] expected stdout 'sidecar-ok'"
    );
    assert_eq!(result.stderr, "", "[infra-001] expected empty stderr");
}

/// [infra-002] sidecar returns exit code 1 for a failing command
#[test]
fn infra_002_sidecar_returns_exit_code_1_for_failing_command() {
    let result = exec_sidecar(
        "sh",
        &["-c", r#"echo "expected-failure-output" >&2 && exit 1"#],
        HashMap::new(),
    )
    .expect("[infra-002] sidecar request failed");
    assert_eq!(result.exit_code, 1, "[infra-002] expected exit code 1");
    assert!(
        result.stderr.contains("expected-failure-output"),
        "[infra-002] expected stderr to contain 'expected-failure-output', got {:?}",
        result.stderr
    );
}
