// Package helpers for the Software Factory test runner.
// Auto-generated by `saifctl feat design`. Do not edit; regenerate with `saifctl feat design <featureName>`.
package helpers

import (
	"bytes"
	"encoding/json"
	"fmt"
	"io"
	"net/http"
	"os"
	"time"
)

// SidecarResponse holds the result of a sidecar command execution.
type SidecarResponse struct {
	Stdout   string `json:"stdout"`
	Stderr   string `json:"stderr"`
	ExitCode int    `json:"exitCode"`
}

var httpClient = &http.Client{Timeout: 30 * time.Second}

// ExecSidecar executes a command in the staging container via the HTTP sidecar.
//
// SAIFCTL_SIDECAR_URL is injected by the Orchestrator (e.g. http://staging:8080/exec).
// Falls back to localhost for local development without the Orchestrator.
func ExecSidecar(cmd string, args []string, env map[string]string) (*SidecarResponse, error) {
	url := os.Getenv("SAIFCTL_SIDECAR_URL")
	if url == "" {
		url = "http://localhost:8080/exec"
	}
	if args == nil {
		args = []string{}
	}
	if env == nil {
		env = map[string]string{}
	}

	payload := map[string]any{"cmd": cmd, "args": args, "env": env}
	body, err := json.Marshal(payload)
	if err != nil {
		return nil, fmt.Errorf("marshal sidecar request: %w", err)
	}

	resp, err := httpClient.Post(url, "application/json", bytes.NewReader(body))
	if err != nil {
		return nil, fmt.Errorf("sidecar request failed: %w", err)
	}
	defer resp.Body.Close()

	if resp.StatusCode != http.StatusOK {
		return nil, fmt.Errorf("sidecar returned status %d", resp.StatusCode)
	}

	var result SidecarResponse
	if err := json.NewDecoder(resp.Body).Decode(&result); err != nil {
		return nil, fmt.Errorf("decode sidecar response: %w", err)
	}
	return &result, nil
}

// BaseURL returns the base URL for the web application in the staging container.
//
// SAIFCTL_TARGET_URL is injected by the Orchestrator. Falls back to staging:3000.
func BaseURL() string {
	if u := os.Getenv("SAIFCTL_TARGET_URL"); u != "" {
		return u
	}
	return "http://staging:3000"
}

// HTTPRequest makes an HTTP request to the staging container web application.
func HTTPRequest(method, path string, headers map[string]string, body any) (*http.Response, error) {
	url := BaseURL() + path

	var bodyReader io.Reader
	if body != nil {
		b, err := json.Marshal(body)
		if err != nil {
			return nil, fmt.Errorf("marshal request body: %w", err)
		}
		bodyReader = bytes.NewReader(b)
	}

	req, err := http.NewRequest(method, url, bodyReader)
	if err != nil {
		return nil, fmt.Errorf("create request: %w", err)
	}
	req.Header.Set("Content-Type", "application/json")
	for k, v := range headers {
		req.Header.Set(k, v)
	}

	return httpClient.Do(req)
}
